### ISSUE TITLE
struggling to get data out of Firebase

### ISSUE THREAD

**Issue by continuata** [crisptrutski/matchbox#34]
I've managed to get the following code working to store a list of pushed objects from my Firebase location into an atom, but it seems rather hacky to me

```clojure
(m/deref fb-root (fn [key] (swap! files #(seq key)))))
```
I then have to call `last` on the items of the sequence (when I'm using `map` on `@files`), as the key is the first item for some reason.

I looked at the async stuff too, but just end up with data structures that I seem incapable of getting anything out of without getting either `nil` or `Error: [object Object] is not ISeqable`.
I want to do something like:

```clojure
(swap! files #(ma/deref< fb-root)) 
```
I'm relatively new to CLJS so potentially doing something utterly stupid ... please help.

**Comment by crisptrutski** [comment]
Hey Stu,

Firebase stores lists as maps, so the `key` parameter in your callback is a clojure map, and `seq` is turning it into a sequence of key-value pairs. Probably `(vals key)` is what you want.

Your values will likely be scrambled due to coming via an (unordered) clojure map - so `deref-list` is probably what you want: `(m/deref-list fb-root #(reset! files %))`. 

Note it's simpler with `reset!` than `swap!`. With channels it would be `(go (reset! files (<! (ma/deref-list< fb-root))))` I think.

As to being "rather hacky", I can point you towards `matchbox.atom`, if you want to keep your atom synchronised. That namespace is experimental and the API is about to change (this week) - probably simplest to explain by linking to example apps in [Om](https://github.com/crisptrutski/matchbox/blob/examples/examples/src/cljs/matchbox_reagent/dice/om.cljs) and [Reagent](https://github.com/crisptrutski/matchbox/blob/examples/examples/src/cljs/matchbox_reagent/dice/reagent.cljs).

**Comment by continuata** [comment]
Thanks Chris,

hugely appreciate the help.
Yes, you were right with `(vals key)` ... that did the trick.

The other (preferred) methods just crash for me with

    FIREBASE WARNING: Exception was thrown by user callback
    ...
    TypeError: undefined is not a constructor (evaluating 'p1__23278_SHARP_.getChildren()') 

This is going to be used by about 0.5M end-users once I roll it out so I really want to get this right.

Cheers

**Comment by crisptrutski** [comment]
Have tried to reproduce quickly - using last 0.0.7-SNAPSHOT and 0.0.6, CLJ and CLJS. 

Can you confirm your platform and which version being used? Reason for asking is that `.getChildren` is only in the JVM API, but that looks like a Javascript exception.

**Comment by continuata** [comment]
it's being used in CLJS Reagent app. (i.e Javascript)
I'm using v0.0.6

**Comment by crisptrutski** [comment]
Mind testing with the 0.0.7 snapshot? Just dug into the asset on clojars, and think 0.0.6 went out with some stale code (CLJX not compiled) - I used the 0.0.6 git tag to test, so wouldn't have triggered it.

**Comment by continuata** [comment]
I get an error with 0.0.7-SNAPSHOT 

    No such namespace: matchbox.core, could not locate matchbox/core.cljs

**Comment by crisptrutski** [comment]
Looks like I've made a pattern of botching deploys. Just updated the snapshot, and tested it from an example project. 

Pushed with the latest version of `matchbox.atom` and `matchbox.reagent` helpers too if you want to try them out (for live sync)

**Comment by continuata** [comment]
any idea how to get leiningen to update a dependency? It's just using the cached version from earlier

**Comment by continuata** [comment]
Got it ... deleted the jar in .m2/repository/matchbox.

It builds ... and now the code works with deref-list :-)

**Comment by crisptrutski** [comment]
Sweet, glad that was it.

Will throw out a release this weekend, main thing is to muster up some better docs, and spruce the demos.

**Comment by continuata** [comment]
this really is a fantastic library.
Reagent plus Matchbox is a great solution for pretty much any web-application, once I've got my head around how to use it all properly.

**Comment by crisptrutski** [comment]
Thanks for the kind words. Also finding Reagent and Firebase to be a potent pair!
