### ISSUE TITLE
deref! returning only value rather than tuple of [key value] in cljs

### ISSUE THREAD

**Issue by tomisme** [crisptrutski/matchbox#37]
From the quickstart:
`(m/deref r safe-prn)
;; => [<key> {:deep {:route "secret"}}]`

But all I am getting back is:
 `{:deep {:route "secret"}}`

I can provide a proper test case (gist) when I get home later if required :)

**Comment by crisptrutski** [comment]
Current behaviour turned out to be more natural, the guide was just out of date here - if you look at the tests for example they're all leaning on this "value only" behaviour for `deref`. The subscription functions on the other hand do return this `[key value]` pair (a poor man's Snapshot)

It's easy to build the old `deref` function out of this implementation:

```clojure
(defn deref-pair [ref cb] (m/deref ref #(cb [(m/key ref) %])))
```

Closing issue, but feel free to continue discussion here

**Comment by tomisme** [comment]
That makes a lot more sense. m/key sounds like what I actually need anyway.
