### ISSUE TITLE
Can't get async to work

### ISSUE THREAD

**Issue by continuata** [crisptrutski/matchbox#42]
I'm calling the following code
```clj
(prn (ma/deref< path))
```
I get the following error
```
#object[clojure.core.async.impl.channels.ManyToManyChannel 0x60eead1e "clojure.core.async.impl.channels.ManyToManyChannel@60eead1e"]
```
Any ideas where I'm going wrong?

**Comment by continuata** [comment]
OK I answered my own question ... I assumed the `matchbox.async` method was doing the taking values from the channel as well as creating it. But it was (as you know) just returning a channel.
Once I required `core.async` and used the `<!!` operator, it worked a charm

```clj
(prn (<!! (ma/deref< path)))
```
Is this the best way of doing this with Matchbox?

I'm basically using Matchbox in a REST API, so I need to block the thread until the Firebase request has returned all the data and I can return the json.

**Comment by crisptrutski** [comment]
@continuata  Glad you figured it out - perhaps another naming scheme like `deref-ch` would have been clearer. 

As to the "best way", it depends on your architecture and application..

If you're using HTTP Kit or Aleph, you'd be better off using go blocks than blocking on the request thread, but for Jetty and other threaded, synchronous servers then `<!!` is perfect.

If you have multiple reads, you'll want to apply `<!!` as late as possible to leverage concurrency. 

ie. rather than:

```clojure
[(<!! (ma/deref< path-a)) 
 (<!! (ma/deref< path-b))]
```

you should use: 

```clojure
(let [a (ma/deref< path-a)
      b (ma/deref< path-b)] 
  [(<!! a) (<!! b)])
```

**Comment by gphilipp** [comment]
@crisptrutski  How can you achieve the same thing from ClojureScript where `<!!` doesn't exist ? I'm in a handler and I have to query the existence of some firebase node and update the db accordingly...

**Comment by crisptrutski** [comment]
When you say `handler` I can assume some sort of `single-db` setup with async actions, ala re-frame? My suggestion with reframe would be to use an impure handler to sync a portion of your db to the node via https://github.com/crisptrutski/matchbox/blob/master/src/matchbox/atom.cljc#L212, then you can `subscribe`, `reaction` or whatever to that portion, and also perform writes to it synchronously from the apps perspective.

**Comment by gphilipp** [comment]
Sorry my post was poorly written. Yes I use re-frame, so I'm talking about a reg-event-fx hander. Here's the code: 

```clojure
(reg-event-fx
    :some-event
    (fn [{:keys [db] :as cofx} event]
        (let [username          (:user db)
              firebase-database (:firebase-database db)]

            ; fetch user (core.async version)
            (let [user-data (-> firebase-database
                                (.ref)
                                (m/get-in [:user username])
                                (ma/deref<))]
                (if user-data
                    ; if user exists...
                    {:db       (assoc db :user-data user-data)
                     :dispatch [:show-user-screen]}

                    ; if user doesn't exist
                    {:db       (assoc db :status :unknow-user)
                     :dispatch [:show-home-screen]})))))
```

My problem if that user-data is a channel, how can I take from that channel and return a {:db...} from the handler. My understanding is that if I wrap it inside a go block, the handler will return immediately with whatever will follow the go block.

**Comment by crisptrutski** [comment]
How about triggering another event from the go block to perform the actual db update?

**Comment by gphilipp** [comment]
Yeah, I've thought about this, but how about having multiple calls being made with if/then/else logic ? Then the logic will be spattered all over the place with "technical" event handlers , not functional ones.

**Comment by crisptrutski** [comment]
Since the actual path is dynamic here, there's really no hope of synchronous reads unless you load *all* users, guessing that's not practical 😄 

The fragmentation issue makes sense, but I was imagining only at most "x2" bloating (a bit like command/query separation). Could collapse all these "commands" if you're ok using a single plumbing handler, ie. takes a diff or swap-fn to apply to the db.

As far as bouncing between reading nodes, go blocks themselves should break up fragmentation - you just need to one to "commit".

One issue with going async (with early return) in handlers is stale / consistent reads against the db value though..
