### ISSUE TITLE
Namespaced keywords?

### ISSUE THREAD

**Issue by prbroadfoot** [crisptrutski/matchbox#49]
I am trying to add matchbox to a re-frame app that uses namespaced keywords in application state, e.g. `:category/active`

Unfortunately this causes Firebase to ignore everything in the keyword before the forward slash. Is there some way to continue using namespaced keywords or is that not supported?

**Comment by crisptrutski** [comment]
Unfortunately this isn't supported right now, mostly due to the use of `walk/stringify-keys` in serialization. 

It wouldn't be a massive stretch to support them. The biggest problem would be that since Firebase paths are URLs, the slash is already used as a path separator. While that's not a train smash, having `{:my/keyword 1}` serialise as `{"my": {"keyword": 1}}` would have disadvantages when it comes to performance and query-ability, and we should perhaps use something like `{"my$keyword": 1}`. 

Then we'd might also want to escape dollar signs too so that it's not ambiguous.. (ad infinitum?)

Sorry for the late reply, have you already found a work around?

**Comment by prbroadfoot** [comment]
Thanks, it's unfortunate this clash occurs but I see now the problem with supporting them. I had a fairly small project, so I decided to un-namespace all of my keywords.

**Comment by crisptrutski** [comment]
@prbroadfoot munging is totally an option and an easy change, just re-open this issue if you change your mind.

On a side note, it usually ends up being necessary to map data to alternate formats over the wire or in the database. This data mapping is elegantly supported in re-frame through decorating the appropriate handlers covering that IO, so don't feel you ever need to compromise your app data, regardless of tools like this one :smile:
